// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdBzmcP5-oULemWk1ga8zRWTi_Do-sPI',
    appId: '1:980675760550:web:79bc4df545d90e6a39ff67',
    messagingSenderId: '980675760550',
    projectId: 'gap1107-9bb56',
    authDomain: 'gap1107-9bb56.firebaseapp.com',
    storageBucket: 'gap1107-9bb56.appspot.com',
    measurementId: 'G-7JHWEEZY56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXb4g7vQuTpx_4n-hHqzruFTW6-hNmF2o',
    appId: '1:980675760550:android:7ee86b07a2b5ac5339ff67',
    messagingSenderId: '980675760550',
    projectId: 'gap1107-9bb56',
    storageBucket: 'gap1107-9bb56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCafCJ5XDXPrKoanCjiqgy7-amuLJ6SZic',
    appId: '1:980675760550:ios:9059136fd7d83b8a39ff67',
    messagingSenderId: '980675760550',
    projectId: 'gap1107-9bb56',
    storageBucket: 'gap1107-9bb56.appspot.com',
    iosBundleId: 'com.example.gap',
  );
}
